image:
  repository: artifactory.dagility.com/docker/vdchecktest-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdchecktest-backend-habitat-prod.dagility.com
    paths:
    - /
serviceAccount:
  create: false
